Dockerfile
The changes to add Amazon S3 file uploads broke the asset precompilation step in `Dockerfile`. This fix adds the environment variables Active Storage is expecting so that it can run.
NB: It doesn't actually need valid values, hence why it gets run with dummy values.
=> (fix) Stop Active Storage breaking build process

app/controllers/reviews_controller.rb, app/views/reviews/new.html.haml, spec/features/user_can_review_completed_spreadsheet_spec.rb, spec/features/users_can_upload_completed_spreadsheet_spec.rb
Source data for an entry is in this format:
```
{
"source": {
"row": 42,
"sheet", "InvoicesReceived"
}
}
```
I had originally used `type` instead of `sheet` and used the wrong names
for the invoices and orders worksheets.
=> (114) ReviewsController now extracts counts correctly

app/controllers/reviews_controller.rb, app/controllers/submissions_controller.rb, app/models/api/submission.rb, app/views/reviews/new.html.haml, app/views/reviews/processing.html.haml, config/routes.rb, lib/validator.rb, spec/features/users_can_review_completed_spreadsheet_spec.rb, spec/features/users_can_trigger_and_view_levy_calculation_spec.rb, spec/fixtures/submission.json, spec/fixtures/submission_with_levy.json, spec/lib/validator_spec.rb
This PR:
- Triggers and polls API for levy calculation when user clicks continue on the review page after validation is successful
- Displays levy calculation to the user
Instead of creating new pages and controllers for the levy calculation polling and display, the `ReviewsController` and `/views/reviews` pages were used for polling both the ingest and the calculate APIs. A `state` query param was added to the `review_processing_path` which will be checked to identify the appropriate url and method to call at the `ReviewsController#processing` action.
Ready for review
=> (123) Do Levy Calculation (Frontend changes)

app/views/reviews/create.html.haml, config/locales/en/reviews.yml, spec/features/users_can_finalise_submission_and_complete_task_spec.rb
Change the copy and remove the reference number. 
Update the specs to reflect the changes.
We do not want to confuse a user with incorrect information or data we
cannot provide in the MVP.
=> (195) Update confirmation page

.rubocop.yml
The default is 100, which is a bit agressive for the stage we're at and
the speed at which we need to go.
=> Increase module length limit in Rubocop config

app/controllers/tools_controller.rb, app/views/shared/_top_navigation.html.haml, app/views/tools/index.html.haml, config/routes.rb, spec/features/users_can_access_a_page_and_download_a_urn_list.rb
Add a tools page with instructions and a link to the URN list.
This is a temporary measure for August so that beta users can lookup URNs.
The file name includes the month as I would like users to be able to
identify the latest copy of the file at a glance, If it turns out we
need to update this file more than once a month we'll need to change
approach, but this is my happy place for now.
I've added a route, controller, view, feature spec and the file.
=> (185) tools page

app/controllers/submission_completion_controller.rb, app/models/api/submission.rb, app/views/submissions/in_review.html.haml, config/routes.rb, spec/features/task_management_spec.rb, spec/fixtures/mocks/submission_completed_with_task.json, spec/support/api_helpers.rb
After the user sees the submission summary page (which shows the number of rows ingested + the levy calculation) and they click the "Complete submission" button, which POSTs to the new
`SubmissionCompletionController#create`.
This calls the API to mark the submission as complete and then redirects to the submission's show page, which now shows the "submission completed" screen along with a flash message.
=> (233) User can mark a submission as completed

app/controllers/home_controller.rb, app/views/home/guest_homepage.html.haml, app/views/home/signed_in_homepage.html.haml, spec/features/users_can_sign_in_spec.rb, spec/features/users_can_view_the_homepage_spec.rb
Show different content to signed-in users that links to their task list.
I've also changed 'log in' to 'sign in' on the guest home page.
=> (224) Signed-in users see a different home page

README.md, RELEASE-PROCESS.md
A simple set of defined steps for releasing the application to production. The aim is to give us a consistent way to release the application that also documents the releases we make.
I expect this to grow and evolve as we learn and do more. Some things that we may want to add to this release process as we move forward:
- a `CHANGELOG` so we have a non-techy way to see exactly what was included in each release
- including the release number (or SHA) somewhere in the markup to make it easier to verify the currently deployed version
- announcing releases somewhere?
=> Add first-pass production release process

RELEASE-PROCESS.md
This tweaks the release process to fit more closely with the existing
process defined in the [DXW playbook]. We still create release PRs and
keep a CHANGELOG up-to-date, but the actual  process of releasing is the
same as in the playbook: manually merging to master.
[DXW playbook]:http://playbook.dxw.com/#/guides/development-workflow?id=deploying
=> Tweak release process to be closer to playbook

Gemfile, Gemfile.lock, config/initializers/rollbar.rb
This is using the default configuration that expects the
`ROLLBAR_ACCESS_TOKEN` environment variable to be set to work.
Additionally, the `ROLLBAR_ENV` can be used to override the environment
on staging (because it runs using the *production* Rails environment).
=> (262) Add Rollbar gem to enable exception tracking

.rubocop.yml, Gemfile, Gemfile.lock, lib/active_storage/service/s3_with_metadata_service.rb, lib/tasks/brakeman.rake, lib/tasks/default.rake, lib/tasks/rubocop.rake
This has been added to the default rake task that is run when you call
`bin/dspec` or `bin/drake` with no options. This will also be included
when CI gets run.
NB: I had to reorganise the rake tasks to ensure that RuboCop, RSpec and
Brakeman were run, as the original `rubocop.rake` was overwriting the
config.
=> (264) Add 'brakeman' to find potential vulnerabilities

.gitignore
We use dotenv-rails to configure environment variables locally. The gem
supports per-environment `.env` files, for example `.env.development`.
By ignoring all `.env` files developers have maximum flexibility to
configure environment variables to suite their environment.
=> Ignore all dotenv files

app/assets/stylesheets/components/_all.scss, app/controllers/submissions_controller.rb, app/views/submissions/in_review.html.haml, app/views/submissions/new.html.haml, spec/features/task_management_spec.rb, spec/fixtures/mocks/submission_completed.json, spec/fixtures/mocks/submission_completed_with_task.json, spec/fixtures/mocks/submission_pending.json, spec/fixtures/mocks/submission_with_entries_errored.json, spec/fixtures/mocks/submission_with_entries_pending.json, spec/fixtures/mocks/submission_with_entries_validated.json
Many suppliers require that invoices they receive include a purchase
order number for them to be payable via their finance system. This makes
it possible for a supplier to include a purchase order number against a
submission.
=> Allow user to set a submission purchase order no.

app/models/api/submission.rb, app/views/submissions/in_review.html.haml, spec/fixtures/mocks/submission_completed.json, spec/fixtures/mocks/submission_completed_with_task.json, spec/fixtures/mocks/submission_pending.json, spec/fixtures/mocks/submission_with_entries_errored.json, spec/fixtures/mocks/submission_with_entries_pending.json, spec/fixtures/mocks/submission_with_entries_validated.json, spec/models/api/submission_spec.rb
The API as of [PR #61] exposes counts for the number of invoices and orders, which means we no longer need to include all the entries to be able to summarise the submission.
[PR #61]: https://github.com/dxw/DataSubmissionServiceAPI/pull/61
=> Use newly exposed entry counts on review page

Dockerfile
The [AWS build] is braking with the latest version of yarn (1.10.0) in a way that we don't understand. To get the build green again so we can hit our October deadline we're going to lock to the known good version of yarn.
[AWS build]: https://eu-west-2.console.aws.amazon.com/codebuild/home?region=eu-west-2#/builds/DataSubmissionService%253Ac2d70c9e-0146-4c9a-a503-80cd290be43b/view/new
=> Lock to yarn 1.9.4

Gemfile, Gemfile.lock, app/models/auth0_authenticated_user.rb, docs/setting-up-new-users.md, spec/models/auth0_authenticated_user_spec.rb
This adds documentation and supporting code for setting up new users on
the Report MI system so that they are able to sign in and make
submissions against their supplier's tasks. For GDPR reasons, a CSV for
October onboarding is not included here in the repository as it would
contain PPI for users.
The process is:
- set up a user in Auth0
- add a User record to the frontend database, including their Auth0
ID, which makes it possible for the user to log in using Auth0.
- Associate the newly created record with their Supplier in the API
by creating a Membership record
When adding the user to Auth0 we set a random password and the user is
asked to use the "reset password" functionality in Auth0 to choose their
own the first time they attempt to log in (they are invited to do so manually).
We …
=> Add utility code and docs for adding new users

app/assets/stylesheets/components/task/_task.scss, app/helpers/submissions_helper.rb, app/views/shared/_task_signpost.html.haml, app/views/submissions/completed.html.haml, app/views/submissions/in_review.html.haml, app/views/submissions/new.html.haml, app/views/submissions/processing.html.haml, app/views/submissions/validation_failed.html.haml, app/views/tasks/_task.html.haml, spec/fixtures/mocks/task_with_framework.json, spec/fixtures/mocks/tasks_with_framework_and_latest_submission.json, spec/helpers/submissions_helper_spec.rb, spec/requests/tasks_spec.rb
We discovered late in the day that there are some users onboarding in October that need to have access to tasks for more than one supplier. This relationship is possible in the API application (i.e. a user can be associated with more than one supplier), but unfortunately the frontend application is currently designed with the assumption that a user will only see tasks for one supplier. Therefor a user that has access to multiple suppliers on the same framework will see duplicate tasks for those frameworks with no way to tell which supplier they are for. 
So that a user is able to distinguish identical tasks across multiple suppliers, we are hijacking the `Task#description` field. When the tasks are seeded for October in the API, any tasks that are for a supplier that has users shared with …
=> Repurpose Task#description to expose supplier name where necessary

app/views/urns/index.html.haml, spec/requests/urns_spec.rb
Leave the August file where it is (on the basis that we don't break the
web unless we can serve a 410)
=> Add September 2018 URN List

app/views/urns/index.html.haml, spec/requests/urns_spec.rb
This PR updates the publicly downloadable URN list.
The new version removes unneeded fields (which reduces the file size).
As part of this, I've also changed the file naming convention so we can handle more than one update a month and also remove the spaces in the file name.
=> Replace public URN list with 2018-01-01 version

app/views/home/guest_homepage.html.haml
The instructions on the home page were a little unclear.
=> (465) Improve 'before you start' copy

Gemfile, Gemfile.lock, config/environments/production.rb
Now we've updated the API to use lograge single line logging, let's do
the same for the app. It'll make the logs easier to search too.
- Stop logging SQL queries
- Use lograge so that one request = one log line (also making it easier
to search!)
- Reduce log_level from 'debug' to 'info' in production(!)
This is the frontend companion to https://github.com/dxw/DataSubmissionServiceAPI/pull/87
=> (476) Reduce logging in production

app/views/no_businesses/new.html.haml, app/views/shared/_task_signpost.html.haml
Using the same task_signpost component created for RMI, in order to be able to change the title thats associated with No Business view,  I modified the task_signpost component partial, using local assigns to fetch the action of the title. The title can then be modified in the No Business view, by calling action and a new title
Added the component into the No Business view
=> Add component called task_signpost to No Business

Dockerfile
This means that both `bash` and the Rails console doesn't break behave strangely when you attempt to type (or paste) the £ (pound) sign.
=> (487) Fix Docker so that you can type '£' into the Rails console

app/assets/stylesheets/components/_all.scss, app/controllers/support_controller.rb, app/helpers/application_helper.rb, app/views/home/guest_homepage.html.haml, app/views/support/frameworks.html.haml, config/routes.rb, spec/features/task_management_spec.rb, spec/features/user_can_submit_no_business_spec.rb, spec/features/users_can_sign_in_spec.rb, spec/features/users_can_upload_completed_spreadsheet_spec.rb, spec/requests/support_spec.rb
We currently show the user which frameworks are submitted through
the new service on the start view. As the number of frameworks grows
this approach was not sustainable.
We decided to add a separate page that lists the frameworks as a interim
solution to this problem with a view to something longer term later.
This change also meant re-wording the content on the start page and
switching to the GOVUK start page pattern which includes the 'start now'
button.
We also took this opportunity to update the support email address which
changed to report-mi@ inline with the service name.
To achieve this we:
- added the back link component
- added a new view to the support controller
- changed the support email address in the helper method
- changed all the content on the start page
- added the …
=> 400 How do we stop the home page getting unwieldy as we add new frameworks?

spec/models/api/task_spec.rb
```
$ rspec --seed 8321
Randomized with seed 8321
F......................................................
Failures:
1) API::Task#late? returns true if the due date has passed
Failure/Error: status == 'completed'
NameError:
undefined local variable or method `status' for #<API::Task:0x00007f94109019a0>
```
It's not clear why this spec would fail sporadically as the internals of
jsonapi-consumer suggest that the instance would only respond to the
`status` method if it was present as an attribute on initialisation.
Either way, it's better for the spec for the status to be explicitly
stated.
=> Fix sporadically failing spec

spec/lib/auditor_spec.rb, spec/support/api_helpers.rb
As tests will fail if you don't have `ccs.api` as your API_ROOT in development.
=> Don't hardcode API_ROOT in tests

CHANGELOG.md
- Update Customer URN file for November
- Automatically update template xls filenames each  month
- Update RM3797.xls
- Don't hardcode API_ROOT in tests
- Bump loofah from 2.2.2 to 2.2.3
=> release-17

app/controllers/tasks_controller.rb, spec/spec_helper.rb, spec/support/api_helpers.rb
As part of removing the user model from this app, we will need to start sending the AuthID (to come straight from Auth0 in the future) to the API.
Also stop allowing real localhost connections in specs, because I don't know why we were, and was making it harder to debug.
=> Send User's Auth ID in API requests

app/models/api/base.rb
As part of opening up the API application to public IPs, we want to add basic authentication to API methods as a backstop should the infrastructure accidentally fail to block requests to it.
=> Add basic authentication to API

app/views/submissions/completed.html.haml, spec/features/task_management_spec.rb, spec/features/user_can_submit_no_business_spec.rb, spec/fixtures/mocks/submission_completed_no_business.json, spec/fixtures/mocks/submission_completed_report_mi.json, spec/requests/submissions_spec.rb, spec/support/api_helpers.rb
Added a way to check that a user is reporting no business or MI.
We introduced a report_no_business? check based on the number of
submission files.
The confirmation page now reflects this change along with new content.
https://trello.com/c/asjZO0fu/596-frontend-confirmation-page-iteration
=> (573) Update the the confirmation page

app/views/submissions/new.html.haml
The label is visually hidden as we had a lot of feedback about this
label being confusing. Screen readers will still see and interpret
the label.
=> (612) Add a label to the submission file upload form

app/views/home/guest_homepage.html.haml, spec/features/task_management_spec.rb, spec/features/user_can_submit_no_business_spec.rb, spec/features/users_can_sign_in_spec.rb, spec/features/users_can_upload_completed_spreadsheet_spec.rb, spec/requests/home_spec.rb
**The problem**
Feedback from DAC report
1. While navigating the Start page, visually impaired users said the 'Before you start' information should be before the start now button. This is to give users context or help before the call to action it relates to.
2. Links on the page: is not descriptive enough of its destination for screen reader users to understand when navigating out of context.
Even though we are following the gov design system on the start page, there is controversy regarding accessibility please see discussion in [GitHub gov start page](https://github.com/alphagov/govuk-design-system-backlog/issues/111)
**Changes made to the PR**
1. 'Before you start' is moved above the start button.
2. 'Start now' is updated as 'Sign in' as this is what it really represents.
4. I have …
=> Feature/617 Accessibility issues with the start page

Dockerfile, app/controllers/templates_controller.rb, app/models/api/task.rb, app/views/no_businesses/new.html.haml, app/views/submissions/completed.html.haml, app/views/submissions/in_review.html.haml, app/views/submissions/new.html.haml, app/views/submissions/processing.html.haml, app/views/submissions/validation_failed.html.haml, app/views/tasks/_task.html.haml, spec/models/api/task_spec.rb
Now we've crossed into the new year we have tasks for both 2018 and 2019. We should show the years to uses to make it easier to determine the exact period for which they are reporting.
https://trello.com/c/z7YW1uIc/668-task-list-add-year-information
=> Include year when showing task reporting period

app/controllers/application_controller.rb, app/models/api/base.rb, app/models/current.rb, spec/models/api/base_spec.rb, spec/support/api_helpers.rb
Uses [ActiveSupport::CurrentAttributes](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html) to allow a model to access the `auth_id` session variable, which is usually only available from controllers.
Thanks @tekin :)
=> (642) Always include current user's 'auth_id' parameter in API requests

spec/fixtures/mocks/submission_completed_no_business.json, spec/fixtures/mocks/submission_completed_report_mi.json, spec/fixtures/mocks/submission_completed_with_task.json, spec/fixtures/mocks/submission_errored.json, spec/fixtures/mocks/submission_validated.json, spec/fixtures/mocks/task_with_invalid_submission.json, spec/fixtures/mocks/task_with_valid_submission.json, spec/fixtures/mocks/tasks_with_framework_and_latest_submission.json, spec/support/api_helpers.rb
I picked this card up from the inbox on a quiet day, I think this is what is needed, but please let me know if not.
After changing the term 'levy' to 'management charge' we realised the API does not return this property at all and so should not be included in the stubs, this removes them.
Resolves:
https://trello.com/c/l2PJ7Mwp
=> (600) Remove management charge (levy) from stubs

RELEASE-PROCESS.md
We noticed during deploy that to keep merge commits in line with the
convention used in the history that we needed to edit the merge commit
message to acknowledge the release. Put that in the process notes.
=> Update release process

config/boot.rb
Bootsnap interferes with debuggers to the extent that breakpoints can't
be hit, so optionally, don't set up bootsnap when a debugger using
`ruby-debug-ide` is detected.
@mec this supersedes the solution you might have seen in your email in that it doesn't require any config change; we just detect the debugger and elect to not set up bootsnap when it's there.
This should let you get away from having to constantly check that the `require` you've commented out isn't being committed by accident 😄 
Source: https://youtrack.jetbrains.com/issue/RUBY-20684#focus=streamItem-27-3183071-0-0
=> Suppress bootsnap require when using a debugger

.env.development.example, .env.test.example, .gitignore, README.md, docs/running-with-docker.md
Move Docker instructions to their own file for legacy's sake
=> (chore) Update README to add non-Docker instructions

app/controllers/errors_controller.rb, app/views/errors/auth_failure.html.haml, app/views/home/guest_homepage.html.haml, config/routes.rb, spec/features/users_can_sign_in_and_out_spec.rb, spec/support/single_sign_on_helpers.rb
When Auth0 authentication fails (for whatever reason) the user was being redirected to `/auth/failure`, which resulted in a 404 and a Rollbar error.
This PR adds an authentication failed page, which invites the user to try logging in again.
=> (feature) Provide a friendly message when authentication fails

spec/models/api/base_spec.rb
This was failing tests on my local machine, and I imagine might for others too.
=> Remove hardcoded API host

app/assets/stylesheets/components/_all.scss, app/controllers/tasks_controller.rb, app/views/tasks/history.html.haml, app/views/tasks/show.html.haml, config/routes.rb, spec/fixtures/mocks/completed_task.json, spec/fixtures/mocks/completed_task_with_no_business.json, spec/requests/tasks_spec.rb, spec/support/api_helpers.rb, yarn.lock
This is the page where suppliers will be able to perform a replacement. We're putting together the bare-minimum page now to unblock the work on replacement returns. Separate work is being carried out to a) expose the extra data we want to display on this page via the API (e.g. uploaded filename, spend totals) and b) update this page to display the new information.
Summary for a business return:
Summary for a no-business return:
=> (815) Introduce show page for completed tasks

app/controllers/tasks_controller.rb, spec/fixtures/mocks/complete_tasks_with_framework_and_latest_submission.json, spec/fixtures/mocks/incomplete_tasks_with_framework_and_latest_submission.json
Now the tasks endpoint on the API supports sparse fieldsets (https://github.com/dxw/DataSubmissionServiceAPI/pull/276), we can restrict which fields are requested, which cuts down the amount of processing the API has to do.
We've updated the request mocks that hit this endpoint, so that any future frontend changes which try to read other fields will result in test failures.
=> (815) Update Tasks#index / Tasks#history to only request fields they need

app/controllers/tasks_controller.rb, app/views/tasks/show.html.haml, spec/fixtures/mocks/completed_task.json, spec/fixtures/mocks/completed_task_with_no_business.json, spec/requests/tasks_spec.rb, spec/support/api_helpers.rb
These are now being exposed by the task API endpoint (https://github.com/dxw/DataSubmissionServiceAPI/pull/281), so we can now display them to the user:
Because the filename is exposed on the `SubmissionFile` model, this association is included in the API request, so the mocks have been updated accordingly.
=> (815) Add invoice/order total values and uploaded filename to Task#show page

app/controllers/submissions_controller.rb, app/views/tasks/show.html.haml, config/routes.rb, spec/features/users_can_download_their_submissions_spec.rb, spec/fixtures/mocks/completed_task.json, spec/fixtures/mocks/completed_task_with_no_business.json, spec/fixtures/mocks/submission_with_file.json, spec/requests/submissions_download_spec.rb, spec/support/api_helpers.rb
On the `Task#show` page, make the submission file downloadable, by clicking on its filename. This sends the user to the `Submissions#download` action which then redirects the user to the temporary (S3) download URL, that gets returned from the API.
NB: I updated the submission id used in `completed_task.json` to use the `mocked_submission_id` value used elsewhere, in order to get the download test to pass. For consistency, I also updated the id used in `completed_task_with_no_business.json`.
=> (834) User can download their submission files

app/controllers/tasks_controller.rb, app/models/api/task.rb, app/views/tasks/_task.html.haml, spec/fixtures/mocks/complete_tasks_with_framework_and_active_submission.json, spec/fixtures/mocks/completed_task.json, spec/fixtures/mocks/completed_task_with_no_business.json, spec/fixtures/mocks/incomplete_tasks_with_framework_and_active_submission.json, spec/fixtures/mocks/task_with_invalid_submission.json, spec/fixtures/mocks/task_with_valid_submission.json, spec/models/api/task_spec.rb, spec/support/api_helpers.rb
Now that we have defined an `active_submission` in the API[1], we can use it everywhere we used to call `latest_submission`.
This step will enable us to remove the deprecated `latest_submission` from the API.
[1] https://github.com/dxw/DataSubmissionServiceAPI/pull/298
Co-authored-by: james <james@abscond.org>
Note: only merge after https://github.com/dxw/DataSubmissionServiceAPI/pull/298 is merged and deployed.
=> Use active_submission instead of latest_submission

app/views/tasks/show.html.haml
Now that the supplier app uses ReportMI Frontend some missing styles
are available, we just needed to add the class name.
We also wrapped the summary list in a two-thirds column to keep it
from becoming too long.
=> Set the class of the show task report no business

app/assets/stylesheets/_settings.scss
When using govuk_table the $govuk-font-family-tabular must be set
to use the custom font setting, otherwise the default will be used.
Thanks to @leeky for the eagle-eyed spot!
=> (fix) Set the correct font for tables

app/controllers/tasks_controller.rb, app/views/layouts/application.html.haml, app/views/layouts/errors.html.haml, app/views/no_businesses/new.html.haml, app/views/shared/_alert.html.haml, app/views/shared/_submission_table.html.haml, app/views/shared/_this_is_a_correction.html.haml, app/views/submissions/completed.html.haml, app/views/submissions/in_review.html.haml, app/views/submissions/new.html.haml, app/views/submissions/processing.html.haml, app/views/tasks/correct.html.haml, app/views/tasks/history.html.haml, app/views/tasks/show.html.haml, spec/features/user_can_correct_submission_with_mi_return_spec.rb, spec/requests/tasks_spec.rb
A number of changes we wanted to make based on user research:
- Changed history page design so that the reported date and reporting month are less confusing.
- 'Report management information' button label on correction view is now 'Correct this return'
- The submission summary table had changed design to be clearer and match the order of the templates, this has also been made into a shared partial for re-use throughout the app.
- The 'This is a correction' flash felt like it was in the wrong section of the app layout so has been moved down
- There is also a fix to the page layout and the alert flashes, the layout had some content in the wrong element and the flashes were using out of date class names.
Does not change the submission summary table on the in review view as this will require …
=> (885) implement replacement returns design from ur analysis

Gemfile, Gemfile.lock
I don't believe there is anything that would require us to restrict the platforms for the mini_racer gem.
This was causing me problems when trying to bundle on OSX Mojave; bundler would try compile libv8 from source, rather than downloading the prebuilt binary that is available.
=> Don't specify explicit platform for mini_racer gem

app/controllers/submissions_controller.rb, app/views/submissions/in_review.html.haml, spec/features/task_management_spec.rb, spec/fixtures/mocks/submission_completed_no_business.json, spec/fixtures/mocks/submission_completed_report_mi.json, spec/fixtures/mocks/submission_completed_with_task.json, spec/fixtures/mocks/submission_errored.json, spec/fixtures/mocks/submission_pending.json, spec/fixtures/mocks/submission_processing.json, spec/fixtures/mocks/submission_validated.json, spec/fixtures/mocks/submission_with_file.json, spec/support/api_helpers.rb
- Use new partial for displaying a submission
- Include the submission files in the API request so that we can
display the file name and link to the file
Showing the file name meant we had to load the submission with the
files included from the API and that means all the mock API calls
had to be updated.
Before:
After: 
Trello: https://trello.com/c/mtq34reF
=> (916) Make changes to the submission in review view

app/views/layouts/application.html.haml
The <title> tag was not getting the default value of 'Report management
information to CCS'. The yield seems to return an empty string object so
is always true.
=> (fix) Page title displays default value

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
We don't use JQuery in any JavaScript (and it's no longer a depency of Rails since UJS is written in pure JavaScript as of Rails v5.1), plus we don't have any CoffeeScript either.
=> Remove unnecessary JS-related dependencies

app/controllers/submissions_controller.rb, app/controllers/tasks_controller.rb, app/models/api/task.rb, app/views/layouts/application.html.haml, app/views/shared/_notice.html.haml, app/views/tasks/_task.html.haml, app/views/tasks/cancel_correction_confirmation.html.haml, config/routes.rb, spec/features/user_can_cancel_correction_spec.rb, spec/features/user_can_correct_submission_with_mi_return_spec.rb, spec/fixtures/mocks/correcting_task.json, spec/fixtures/mocks/correcting_task_with_framework.json, spec/fixtures/mocks/correcting_task_with_framework_and_active_submission.json, spec/fixtures/mocks/incomplete_tasks_with_framework_and_active_submission.json, spec/requests/tasks_spec.rb, spec/support/api_helpers.rb
User can view the tasks where they have an incomplete correction submission on the homepage.
Tasks are marked as `correcting` when uploading a correction return.
User can cancel the correction. The correction files are deleted.
Note: this PR depends on https://github.com/dxw/DataSubmissionServiceAPI/pull/328 being merged and deployed.
=> (818) Incomplete correction submission

app/views/submissions/new.html.haml
Once a user has started a business submission, they had no way of restarting the task and submitting no business instead. This led to support requests to reset tasks for users that wanted to do this.
This is resolved by simply putting this link into the new submission page, which is accessible from both the validation failed and in review states of an existsing submission.
=> Allow users to replace return in errors with no business

config/initializers/load_cloud_factory_service_variables.rb, lib/vcap_parser.rb, spec/lib/vcap_parser_spec.rb
As part of moving to GPAS, we need to be able to load environment variables from VCAP_SERVICES as specified in https://docs.cloudfoundry.org/buildpacks/ruby/ruby-service-bindings.html
I tried using the cf-app-utils gem, but it's out of date, and was more trouble than just parsing the JSON manually.
=> Configure Service Connection Environment variables

lib/vcap_parser.rb, spec/lib/vcap_parser_spec.rb
In GPAAS, the S3 bucket configurations are given to us in the VCAP_SERVICES JSON.
This commit looks for an S3 bucket with a GPAAS name beginning with `ingest-bucket, and load that bucket's credentials to the ENV.
=> Load S3 bucket config to ENV from VCAP

CF/deploy-app.sh
This means that new apps will be brought up with the correct number of
instances and memory when first deployed.
=> Move HA settings to after CF_SPACE is set

CF/manifest-template.yml
These environment variables are the same in both environments and are
not secrets so add them to manifest template.
=> Add non secret environment variables to the manifest template

app/controllers/urns_controller.rb, app/models/api/urn_list.rb, app/views/urns/show.html.haml, config/routes.rb, spec/fixtures/mocks/urn_lists.json, spec/fixtures/mocks/urn_lists_empty.json, spec/requests/urns_spec.rb, spec/support/api_helpers.rb
Fetch the latest URN list using the new `GET /v1/urn_lists` endpoint and display the details to the user. If a valid URN list is not available, we fallback to the existing one. 
**Depends on: https://github.com/dxw/DataSubmissionServiceAPI/pull/439**
=> (1050) Fetch URN list from API and allow user to download it

CF/deploy-app.sh
The v3 cf-cli commands deal with zero down time deploys better.
In particular our network policy to talk to the internal API was not
dealt with correctly by the blue-green plugin.
=> Use v3 cf-cli commands to make deploys better

app/controllers/submissions_controller.rb, app/models/api/task.rb, app/views/submissions/ingest_failed.html.haml, app/views/tasks/_submission_buttons.html.haml, spec/fixtures/mocks/task_with_submission_that_failed_ingest.json, spec/models/api/task_spec.rb, spec/support/api_helpers.rb
This will be displayed when ingest fails to process a file, which will allow the user to continue without intervention from support.
NB: This won't actually be visible to users until changes are made to the API, but wanted to have this in place ready.
=> (1043) Add additional page for a submission in the 'ingest_failed' state

app/controllers/submissions_controller.rb, app/views/submissions/ingest_failed.html.haml, app/views/tasks/_submission_buttons.html.haml
In the new ingest failed page, we didn't pass through the correction param flag on the retry button, which led to users trying to submit a new submission against a completed task, resulting in confusing error messages.
=> (1093) Don't forget if submission is a replacement on ingest failed

Gemfile, Gemfile.lock, app/views/home/guest_homepage.html.haml, spec/features/task_management_spec.rb, spec/features/user_can_cancel_correction_spec.rb, spec/features/user_can_correct_submission_with_mi_return_spec.rb, spec/features/user_can_correct_submission_with_no_business_spec.rb, spec/features/user_can_submit_no_business_spec.rb, spec/features/users_can_download_their_submissions_spec.rb, spec/features/users_can_upload_completed_spreadsheet_spec.rb
Github recently raised a security notification for all projects relying on omniauth, but omniauth don't have a fix for this yet. (see omniauth/omniauth#809)
I'm therefore leaning towards what @tekin has done with DFE-Digital/dfe-teachers-payment-service#104 and locking down the get action anyway, using the omniauth-rails_csrf_protection gem.
=> Address CVE-2015-9284

CHANGELOG.md
- Don't forget if submission is a replacement on ingest failed
- Address CVE-2015-9284
- Use JWT for API authentication
=> Release 50

app/controllers/submissions_controller.rb, spec/fixtures/mocks/submission_with_file.json, spec/requests/submissions_download_spec.rb, spec/support/api_helpers.rb
Because GPAAS doesn't allow us to use temporary_download_url, we need to use the AWS S3 library to retrieve the file to then send to the supplier.
=> Use AWS API for supplier downloading submission file

app/views/shared/_header.html.haml, spec/features/users_can_sign_in_and_out_spec.rb
Now that we forbid GET requests to omniauth sign in for security reasons, the header would either need to be a button, or not exist. After speaking to @mec, we've decided to remove it.
=> Remove Sign In Link in header

app/controllers/submissions_controller.rb, spec/requests/submissions_download_spec.rb
For some reason, on intermittent CI builds, AWS_S3_REGION is not set,
causing this error in the aws-partitions gem:
```
NoMethodError:
undefined method `match' for nil:NilClass
```
Avoid using a real S3 client at all so we don't have to configure it by
supplying a spy instead, and check we talked to our fake S3 with the
`file_key` we mocked.
While here, change the title of the example, which referred to what it
used to do.
=> Fix occasional build failure

docker-compose.env.sample, docker-compose.yml
* There was no way for this projects web conainter to make connections using `ENV['API_ROOT'] => localhost:3000` to communicate with the API project/containers that support it with data.
* We have made a change to the API to expose itself via a public Docker network, under the alias `api`. This will now allow us to make requests to api:3000 and Docker will be able to resolve that domain name to a dynamic IP.
* This does introduce an explicit dependency between this application and the API, it will not be able to start without the presence of a API network. This can be created to allow the app to boot independently following the Docker-compose error prompt. The alternative in the non-docker world would be for the app to boot without an API being started but for the first request to fail. …
=> (chore) Web can make requests to the API via Docker

docker-compose.test.yml, docker-compose.yml
* Before this change starting the container from a clean state would result in asset pipeline errors generated by gov-uk frontend assets being unavailable.
* Eventually we tracked down that whilst the install process in the Dockerfile was installing the packages correctly and putting them within the image, they were being overwritten by the docker-compose volume configuration.
* The configuration of `.:/srv/dss` said, mount all the files from my local directory into the directory the Docker Image had prepared, in `/srv/dss` - this is very helpful in development since we don't want to rebuild the docker image every time we want to refresh the webpage or run the test suite.
* This change says that the `node_modules` directory should be mounted to a prepared Docker volume which stores the …
=> (chore) Fresh docker builds will provision node_module dependencies

app/views/tasks/_submission_buttons.html.haml, spec/requests/tasks_spec.rb
A user who is trying to correct their return from the 'view errors' page
would cause a 500 error because the 'correction' param was not set.
=> Add the correction param to view errors button

CF/manifest-template.yml
In production we have 2 different AUTH0 clients with different levels of
access.
Make the APP use the one with the access the APP needs.
=> Use an app specific AUTH0 user service

CF/create-user-services.sh, CF/user-services.json
The API and frontend app have different credentials with AUTH0 because they
have different levels of access.
=> Create a user service for the API and APP for AUTH0

bin/drails, bin/drake, bin/dspec
This puts the bash variable $@ in double quotes, so that shell words are
preserved correctly. For example, if one runs:
./bin/dspec -e 'name of test'
Then there are two argument strings passed to `dspec`: `-e`, and `name
of test`. The bash variable $@ contains these two strings. If it's used
unquoted, the effect is to insert them into a command as though they had
not been quoted originally, resulting in a command like this being run:
docker exec ... rspec -e name of test
That means `rspec` is run with the arguments: `-e`, `name`, `of` and
`test`; `name` is used to match tests by name, and `of` and `test` are
assumed to be filenames, which results in an error.
Quoting the $@ variable effectively preserves the original quoting of
the shell words, so we get this instead:
docker exec ... …
=> (fix) Correct use of $@ in shell scripts

Gemfile, Gemfile.lock
Previous version were vulnerable - see https://nvd.nist.gov/vuln/detail/CVE-2019-5477 for details
NB: running `bundle update nokogiri` failed, so fixed by explicitly declaring a minimum version in Gemfile.
=> Bump nokogiri to v1.10.4

app/controllers/submissions_controller.rb, app/models/api/task.rb, app/views/tasks/_submission_buttons.html.haml, spec/fixtures/mocks/incomplete_tasks_with_framework_and_active_submission.json, spec/fixtures/mocks/submission_management_charge_calculation_failed.json, spec/fixtures/mocks/task_with_submission_that_failed_management_charge_calculation.json, spec/models/api/task_spec.rb, spec/requests/submissions_spec.rb, spec/requests/tasks_spec.rb, spec/support/api_helpers.rb
- Handle the new (edge case) `management_charge_calculation_failed` submission status, added to the API in dxw/DataSubmissionServiceAPI#505. Display a generic error message and return a 500 status if the user tries to view the details of the errors (see commit message for further justification).
Error page displayed when trying to view a submission with this status:
=> [1140] Handle the new management_charge_calculation_failed submission status

Gemfile, Gemfile.lock
This reverts commit dcc27893ecac2d44dd8e04c06cc6bc5342a0a5bc, reversing
changes made to 238ea3f1ce2020a9d85403f4897ca5c81e02ad41.
Whilst we have already merged a fix for this Nokogiri vulnerability https://github.com/dxw/DataSubmissionService/pull/270 we attempted another change because the GitHub security advisory was still displaying on the repository page, and we had received another warning email. We also believe that the changes made in this change better protect the team from accidentally reverting back to a vulnerable version of Nokogiri due tot he explicit lock `'>= 1.10.4'`.
Updating the Nokogiri gem using bundler 2.0.2 was fine during the the build phase and so was merged. However, when CI came to deploy this change the Ruby on Rails buildpack was using bundler 2.0.1 which fails …
=> Revert "Merge pull request #275 from dxw/security/update-nokogiri"

Dockerfile, Gemfile, Gemfile.lock
- ensure we are using the same version of Bundler as used on the PaaS for now
- explicit lock on the Nokogiri gem to preserve the change made to the gemfile.lock by Dependabot and ensure we do not allow another gem to take us backwards - what do you think of this?
- paired with https://github.com/dxw/DataSubmissionServiceAPI/pull/512
=> Security/lock nokogiri to 1.10.4

app/assets/javascripts/main.js, app/views/layouts/application.html.haml, app/views/layouts/errors.html.haml, config/environments/production.rb, config/initializers/content_security_policy.rb
Add the following response headers:
- `Strict-Transport-Security` - lets a web site tell browsers that it should only be accessed using HTTPS, instead of using HTTP.
- `Content-Security-Policy` -  restricts the locations from which a browser will download or execute resources such as images, scripts, etc. It does this using a per-response whitelist. An additional layer of defence against attacks such as cross-site scripting.
- `Expect-CT` - tells the browser that if communicating with a web site over HTTPS, then the certificate presented by the web site must meet Certificate Transparency requirements. This means that the certificate must have been added to a public log.
_See commit messages for more details._
My understanding, from our discussion of the original ticket, is that this list …
=> [1096] Add some security-related HTTP response headers

config/initializers/content_security_policy.rb
With the Content-Security-Policy response header introduced in bc12b64,
I broke Google Analytics on production. It is able to load the script
from the whitelisted https://www.googletagmanager.com, but it turns out
that this script then attempts to load another script from
https://www.google-analytics.com.
This is the error that Chrome gives me:
gtm.js?id=GTM-TQNKLQS:361 Refused to load the script 'https://www.google-analytics.com/analytics.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
I think I misread the (linked) documentation and assumed that you had to
_either_ whitelist the Google Tag Manager …
=> [1096] (fix) Fix Google Analytics by expanding Content-Security-Policy whitelist

app/helpers/application_helper.rb, app/views/layouts/application.html.haml, app/views/layouts/errors.html.haml, app/views/support/index.html.haml
Change the survey URL, as requested in a support ticket. Whilst I'm at it, I've DRYed it up so we only specify the URL in one place.
=> Change survey URL

app/assets/stylesheets/components/_all.scss, app/assets/stylesheets/components/flash/_flash.scss, app/views/submissions/processing.html.haml
Following an accessibility audit, we've been asked to make some small changes to the processing page, namely increasing the refresh timeout (presumably so screenreaders have time to read the content of the page before it refreshes) and moving the note about what is happening further up the page. Going by the HTML, I don't think this will break anything, but I can't run the application properly to confirm this. I'd be grateful if someone with more experience than me could review this for me 😄
=> Accessibility tweaks to processing page

Gemfile, Gemfile.lock, app/views/shared/_submission_table.html.haml, spec/features/users_can_upload_completed_spreadsheet_spec.rb, spec/fixtures/mocks/completed_task.json, spec/fixtures/mocks/completed_task_with_no_business.json, spec/fixtures/mocks/correcting_task.json, spec/fixtures/mocks/correcting_task_with_framework_and_active_submission.json, spec/fixtures/mocks/submission_completed_no_business.json, spec/fixtures/mocks/submission_completed_report_mi.json, spec/fixtures/mocks/submission_completed_with_task.json, spec/fixtures/mocks/submission_errored.json, spec/fixtures/mocks/submission_management_charge_calculation_failed.json, spec/fixtures/mocks/submission_pending.json, spec/fixtures/mocks/submission_validated.json, spec/fixtures/mocks/submission_with_file.json
Show users the count of submitted 'other' rows on the summary page.
=> (1183) Add an other section to the submitted return summary

app/views/errors/auth_failure.html.haml, spec/features/users_can_sign_in_and_out_spec.rb
Change 'Sign in' button on the authentication failure page (/auth/failure/) to make a POST request, preventing users ending up on the 404 page.
=> (1115) Prevent users getting stuck after auth failure

app/controllers/support_controller.rb, app/views/home/guest_homepage.html.haml, app/views/support/frameworks.html.haml, spec/requests/home_spec.rb, spec/requests/support_spec.rb
ReportMI now handles submissions for *all* frameworks, so we can remove both the link to MISO and the list of supported frameworks.
=> (1196) Tidy up support pages, now we've replaced MISO

app/views/submissions/processing.html.haml
At the request of the client who felt 30 seconds is too long.
This change was introduced as part of an accessibility audit, but the
length of time was not mentioned.
=> Adjust refresh timer on processing view

.dockerignore, docker-compose.env.sample, docker-compose.test.yml, docker-compose.yml
This fixes the local Docker development environment, which has been broken for a while. I can now successfully:
- run the server with `bin/dstart` and access it at `http://localhost:3100`
- run the tests with `bin/dtest-server` and `bin/dspec`
The changes are similar to https://github.com/dxw/DataSubmissionServiceAPI/pull/628.
You'll need to update your local `docker-compose.env` with the new `DATABASE_URL` from `docker-compose.env.sample`.
=> Fix local Docker development environment

CHANGELOG.md, app/views/layouts/application.html.haml, app/views/layouts/errors.html.haml
RMI-27
No longer in Beta.
No
Locally and visually.
=> RMI-27-Remove-Beta-Banner

.travis.yml, CHANGELOG.md, Gemfile, Gemfile.lock
RMI-343
GDS ruby buildpacks support is ending for 2.5.7 ruby versions.
No.
[X] Breaking change
Smoke test/ran the app and tested.
=> Update ruby version from 2.5.7 to 2.5.8

app/controllers/sessions_controller.rb, config/routes.rb, lib/auditor.rb
RMI-333
Conclave session management work - Required for SSO integration.
API:
'session_store.rb'
'events_controllers.rb'
'user_terminated.rb'
[X] New feature
=> RMI-333-Session-Management

.travis.yml, CF/create-cf-space.sh, CF/create-user-services.sh, CF/deploy-app.sh
This is a fix for the 'preprod' environment in CF being renamed to 'conclave-development'.
All apps and services are still ending with "-preprod" in conclave-development env, so this is a fix for the pipeline, to continue deploying as normal. Compatible with all of our envs/branches now.
=> Conclave-Deployment-Fix

.travis.yml, CF/create-cf-space.sh, CF/create-user-services.sh, CF/deploy-app.sh
This is a fix for the 'preprod' environment in CF being renamed to 'conclave-development'.
All apps and services are still ending with "-preprod" in conclave-development env, so this is a fix for the pipeline, to continue deploying as normal. Compatible with all of our envs/branches now.
=> Conclave deployment fix

app/views/errors/auth_failure.html.haml, app/views/home/guest_homepage.html.haml
RMI-335
Tidy up and remove old testing links, for the sso, now it is implemented.
No.
[X] Bug fix
=> CON-335-Remove-Old-Testing-Links

config/environments/production.rb
RMI-478
Invalid HTST config.
No
[X] Bug fix
Documentation confirmed.
=> RMI-478-Update-HTST-Config

config/initializers/content_security_policy.rb
Add glassbox domains to CSP whitelist
https://crowncommercialservice.atlassian.net/browse/RMI-516
To allow use of Glassbox service
No
N/A
=> RMI-516 Amend CSP

CHANGELOG.md, app/views/home/guest_homepage.html.haml, app/views/no_businesses/new.html.haml, app/views/submissions/completed.html.haml, app/views/support/frameworks.html.haml, app/views/support/index.html.haml, app/views/tasks/_no_tasks.html.haml, app/views/tasks/correct.html.haml, app/views/tasks/history.html.haml
RMI-401
"Framework" usage is being refined out by CCS, and so this replaces any UI viewable instances with "Agreement", as required.
No, but same changes also made in the API.
Non required, as there are no functional or server changes, they are only superficial changes.
=> RMI-401-Replace-Framework-Terminology

app/views/agreements/_agreements.html.haml
Added status filter to agreements page (used tags to show whether agreements are active or inactive), and updates the tag being used.
https://crowncommercialservice.atlassian.net/browse/RMI-419
Improve user experience
Update in API must be deployed
Manually
=> Update active css govuk tag

app/views/agreements/_agreements.html.haml
Added status filter to agreements page (used tags to show whether agreements are active or inactive), and updates the tag being used.
https://crowncommercialservice.atlassian.net/browse/RMI-419
Improve user experience
Update in API must be deployed
Manually
=> Update active tag colour

docker-compose.build.yml, docker-tests.sh
This allows us to build a docker image and run those tests from a single command docker-tests.sh
https://crowncommercialservice.atlassian.net/browse/GMBP-97
=> GMBP-97: Allow RMI (frontend) to build and run tests within Jenkins

app/controllers/submission_completion_controller.rb
- [NRMI-85: Fix for error page on submit when session has ended](https://crowncommercialservice.atlassian.net/browse/NRMI-85)
Improved user experience and reduce support queries
No
[X] Bug fix
Manually
=> NRMI-85: fix for session end error page

app/views/submissions/ingest_failed.html.haml, app/views/submissions/validation_failed.html.haml
- [NRMI-86: Add back link to post submission validation pages](https://crowncommercialservice.atlassian.net/browse/NRMI-86)
Consistency with all journeys from tasks page, improved user experience.
No
Manually
=> feature/nrmi-86: add back button to all task submission output pages

app/views/submissions/completed.html.haml, spec/features/user_can_bulk_report_no_business_spec.rb
- [NRMI-114: update 'what happens next' wording](https://crowncommercialservice.atlassian.net/browse/NRMI-114)
Reduced support query / improved self serve mindset for supplier users.
No
Feature and manual test
=> NRMI-114: update wording on tasks complete page
