Crown-Commercial-Service/DataSubmissionService

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/tasks_controller.rb
- app/views/layouts/application.html.haml
- app/views/shared/_top_navigation.html.haml
- spec/controllers/application_controller_spec.rb
- spec/factories/user.rb
- spec/features/user_can_review_completed_spreadsheet_spec.rb
- spec/features/users_can_upload_completed_spreadsheet_spec.rb
- spec/features/users_can_view_and_complete_tasks_spec.rb
- spec/support/api_helpers.rb
- spec/support/factory_bot.rb
- Only signed-in users can see the list of tasks
- A user can only see their own tasks (currently those assigned to their `Supplier`)
Depends on: https://github.com/dxw/DataSubmissionServiceAPI/pull/6
> (125) Link users and suppliers

- testspec.yml
* Rns the required tests in CodeBuild
> (Chore) Add testspec.yml

- app/views/layouts/application.html.haml
* added the link in the phase banner
> (145) add a beta banner that asks for feedback

- app/views/home/index.html.haml
- app/views/layouts/application.html.haml
- app/views/shared/_top_navigation.html.haml
Changed the service name to reflect the current thinking:
* Service name: Report management information to CCS
* Changed: title tag, global header, home page
> (192) Change service name

- app/views/layouts/application.html.haml
Add a mailto support link to the footer.
https://trello.com/c/CD3L69Qe
> (4) support email link

- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_tasks.scss
- app/views/submissions/nil_return.html.haml
- app/views/tasks/_task.html.haml
Changes to around the 'nil return' turning into 'Report no business'
- task button with hint
- confirmation page
- styles
> (152) Change nil return language

- app/views/home/index.html.haml
- spec/features/users_can_download_template_spec.rb
- spec/features/users_can_finalise_submission_and_complete_task_spec.rb
- spec/features/users_can_review_completed_spreadsheet_spec.rb
- spec/features/users_can_sign_in_spec.rb
- spec/features/users_can_trigger_and_view_levy_calculation_spec.rb
- spec/features/users_can_upload_completed_spreadsheet_spec.rb
- spec/features/users_can_view_tasks_spec.rb
Add some basic content to the home/sign in view.
The content reflects our current thinking for this but is likely to
change.
https://trello.com/c/kVj9QtXY
> (201) add basic content to home view

- terraform/terraform.tf
* Was unable to run terraform apply because the ECR already existed
* Wil now use a different ECR per workspace
> (Fix) Append workspace to ECR name

- app/assets/stylesheets/components/_tasks.scss
- app/helpers/application_helper.rb
- app/views/tasks/_empty_task.html.haml
- app/views/tasks/_task.html.haml
- app/views/tasks/index.html.haml
- config/initializers/date_format.rb
Checks the status of a task and displays the relevant UI. We check for in_progress and completed.
At the moment a complete task will show up in the list but will have no navigation.
> (182) Users know the status of their tasks from their task list

- app/views/support/index.html.haml
We added a missing paragraph to the support page.
> (165) add updated content to support page

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/submission_completion_controller.rb
- app/controllers/submissions_controller.rb
- app/controllers/tools_controller.rb
- app/controllers/urns_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/application.html.haml
- app/views/no_businesses/new.html.haml
- app/views/shared/_alert.html.haml
- app/views/shared/_top_navigation.html.haml
- app/views/submissions/completed.html.haml
- app/views/submissions/in_review.html.haml
- app/views/tasks/_task.html.haml
- app/views/urns/index.html.haml
- config/initializers/date_format.rb
- config/routes.rb
- spec/features/task_management_spec.rb
- spec/features/users_can_access_a_page_and_download_a_urn_list_spec.rb
- spec/features/users_can_sign_in_spec.rb
- spec/features/users_can_upload_completed_spreadsheet_spec.rb
- spec/support/capybara.rb
Various content tweaks and adjustments based on feedback from a full app design crit
> 249 content tweaks

- app/views/urns/index.html.haml
Change content on URN list page.
> (257) Adjust wording on URN list page

- app/views/urns/index.html.haml
> Update content on urns page

- app/assets/javascripts/main.js
Once the window is loaded we can initalise the GOVUK Frontend JS.
> (fix) initalise JS on window load

- app/views/layouts/application.html.haml
- app/views/layouts/errors.html.haml
- app/views/shared/_analytics.html.haml
In order to setup our events in the web UI rather than code we
need to switch to Tag Manager tracking from GA tracking:
https://support.google.com/tagmanager/answer/7582054?hl=en&ref_topic=3441530&authuser=0
> Switch to Google Tag Manger for tracking

- app/assets/stylesheets/components/_all.scss
- app/assets/stylesheets/components/task_signpost/_task_signpost.scss
- app/views/shared/_task_signpost.html.haml
- app/views/submissions/in_review.html.haml
- app/views/submissions/new.html.haml
- app/views/submissions/processing.html.haml
- app/views/submissions/validation_failed.html.haml
A user can see which task and framework they are submitting on throughout the journey.
Created the partial and styling for that component
Created the component in the four views that needed it
> Add component called task_signpost

- app/views/submissions/validation_failed.html.haml
- spec/features/task_management_spec.rb
This was mistakenly removed by #d138a60ca84ac69.
> Re-instate link to upload amended submission file

- app/views/home/guest_homepage.html.haml
> Update homepage with migrated October frameworks

- app/views/urns/index.html.haml
We should be sharing an XLS file, not XLSX
> 462 replace september url file

- docs/setting-up-new-users.md
Having now performed this for real we have a better sense of how this
needs to work on production:
- Better signposting on how to get the CSV file into the docker
container
- Handling for users that have access to more than one supplier
- Add a sleep to keep Auth0's rate limiting happy
> Tweak setting up new users script

- app/views/urns/index.html.haml
- spec/requests/urns_spec.rb
File provided by CCS, stripped of the test customers and columns not relevant to suppliers.
> Update Customer URN file for November

- app/views/urns/index.html.haml
- spec/requests/urns_spec.rb
Relates to https://trello.com/c/IlxAnpXM/610-update-customer-urn-list
> Update URN List Spreadsheet

- app/assets/stylesheets/components/tags/_tags.scss
- app/assets/stylesheets/components/task/_task.scss
- app/views/tasks/_submission_buttons.html.haml
- app/views/tasks/_task.html.haml
- app/views/tasks/index.html.haml
Initial work to improve the accessibility of the task page and tasks.
Made the task list use a ul element and reorder some of the content.
Added some aria-labels to aid SR users.
Changes the colours of some of the tags to meet contrast requirements.
Resolves:
https://trello.com/c/cVwlQwNN
> (616) accessibility issues with task component

- Gemfile
- Gemfile.lock
As this project is open source, the SKYLIGHT_AUTHENTICATION setting should be set in an ENV varibiable.
> Add skylight gem

- app/views/support/frameworks.html.haml
> Add RM1043.5 to list of frameworks we handle

- RELEASE-PROCESS.md
After another paired run-through, this time with @lozette, find and make explicit more slightly
vague areas
> Iterate release process

- CHANGELOG.md
- Provide friendly message when authentication fails
> Update Changelog for release 30

- app/controllers/tasks_controller.rb
- app/models/api/task.rb
- app/views/shared/_header.html.haml
- app/views/tasks/history.html.haml
- app/views/tasks/index.html.haml
- config/initializers/date_format.rb
- config/routes.rb
- spec/features/task_management_spec.rb
- spec/features/user_can_submit_no_business_spec.rb
- spec/features/users_can_sign_in_and_out_spec.rb
- spec/fixtures/mocks/complete_tasks_with_framework_and_latest_submission.json
- spec/fixtures/mocks/incomplete_tasks_with_framework_and_latest_submission.json
- spec/requests/tasks_spec.rb
- spec/support/api_helpers.rb
Some questions: Do we want a link back to tasks index page from history page?
We are not including the links to view a completed task yet, as @leeky is working on that.
> 814 supplier can view list of history of tasks

- public/analytics.txt
Has a token in to prove access to Google and an instruction to add
Timur as an administrator.
> Add analytics.txt with content from Timur

- CHANGELOG.md
- Add analytics.txt for Google Analytics
> CHANGELOG for Release 31

- Gemfile
- Gemfile.lock
- app/controllers/no_businesses_controller.rb
- app/controllers/tasks_controller.rb
- app/helpers/application_helper.rb
- app/views/no_businesses/new.html.haml
- app/views/submissions/completed.html.haml
- app/views/tasks/correct.html.haml
- app/views/tasks/history.html.haml
- app/views/tasks/show.html.haml
- config/routes.rb
- spec/features/user_can_correct_submission_with_no_business_spec.rb
- spec/features/user_can_submit_no_business_spec.rb
- spec/fixtures/mocks/complete_tasks_with_framework_and_latest_submission.json
- spec/requests/tasks_spec.rb
- spec/support/api_helpers.rb
* Replace submission page and actions
* Linking from the completed task page and feature spec for it
> (816) Supplier can replace submission with no business

- CHANGELOG.md
Use active_submission instead of latest_submission
> Release 35

- app/controllers/application_controller.rb
- app/controllers/no_businesses_controller.rb
- app/controllers/submission_completion_controller.rb
- app/controllers/submissions_controller.rb
- app/views/no_businesses/new.html.haml
- app/views/shared/_this_is_a_correction.html.haml
- app/views/submissions/completed.html.haml
- app/views/submissions/in_review.html.haml
- app/views/submissions/new.html.haml
- app/views/submissions/processing.html.haml
- app/views/tasks/correct.html.haml
- spec/features/user_can_correct_submission_with_mi_return_spec.rb
- spec/features/users_can_upload_completed_spreadsheet_spec.rb
- spec/rails_helper.rb
- spec/support/api_helpers.rb
NB: This PR must wait for https://github.com/dxw/DataSubmissionServiceAPI/pull/308 to be merged and deployed to prod before it can be merged.
> (911) Supplier can correct a submission by uploading an MI return

- RELEASE-PROCESS.md
We are doing this currently, so it should be documented.
> Edit release process notes

- app/views/home/guest_homepage.html.haml
- app/views/home/signed_in_homepage.html.haml
- app/views/submissions/completed.html.haml
- app/views/submissions/new.html.haml
- app/views/support/frameworks.html.haml
- app/views/support/index.html.haml
- app/views/tasks/index.html.haml
- spec/requests/home_spec.rb
This is all the content changes I think we can do without making backend changes, that means no:
- framework > commercial agreement
- task > return
- submit > report
tasks:
support (beofre supplier corrections enabled):
completed:
new: 
home (signed in):
home (signed out):
> (833) Service copy review implementation

- app/views/support/index.html.haml
This is the content for the support page once self-service corrections
are enabled.
Trello: https://trello.com/c/xqlohNYO
> (924) Updated content for support page

- CHANGELOG.md
- Allow users to replace return in errors with no business
> Release 45

- CF/create-user-services.sh
- CF/user-services.json
* Also fixes an absent auto0 env
> (Chore) Add api router service

- .rubocop.yml
- .travis.yml
We want to run CI and deployments from travis.
> Add a `.travis.yml`

- CF/ccs-rmi-cdn-prod.json
- CF/ccs-rmi-cdn-staging.json
- CF/create-cf-space.sh
We want to put prod and staging behind a CDN so we can use a custom
domain. This sets up the domains in the org and creates the CDN service.
> Create domains and CDN routes for prod and staging

- CHANGELOG.md
- spec/requests/templates_spec.rb
- Allow downloading of framework templates from API
> Release 47

- PULL_REQUEST_TEMPLATE.md
* Following the set up from GitHub: https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository
* This template will help prompt the current and future teams into providing helpful information into the description for both the review itself and to serve as documentation in the future.
> (chore) Add a pull request template for GitHub

- app/views/accessibility/index.html.haml
We'll soon be fully WCAG 2.1 compliant :)
> (1173) Update the accessibility statement

- CF/manifest-template.yml
- CHANGELOG.md
> Added Splunk monitoring

- CHANGELOG.md
New pull request template, SimpleCov set up and Code Climate set up in Travis build
For RMI-246 and reflecting process changes
No.
[X] This change requires a documentation update
N/A
> release-64

- .travis.yml
- CF/ccs-rmi-cdn-preprod.json
- CF/ccs-rmi-cdn-prod.json
- CF/ccs-rmi-cdn-staging.json
- CF/create-cf-space.sh
- CF/deploy-app.sh
- CF/routing-readme.md
- CHANGELOG.md
RMI-275
We had set up a new environment in cloud foundry for Preprod, which needed integrating with git/travis.
[X] This change requires a documentation update
Push into new branch.
> Fix/RMI-275 Add Preproduction environment to Github/Travis existing infrastructure

- CHANGELOG.md
Ensuring Changelog accurately reflects changes to be deployed.
As above.
No.
N/A
N/A
> updated changelog ahead of release-67

- app/views/support/index.html.haml
Amendments based on QA feedback:
https://crowncommercialservice.atlassian.net/browse/RMI-294?focusedCommentId=29413
QA feedback
No.
Wording changes.
Unit and manual testing
> RMI-294 amendment

- app/assets/stylesheets/reportmi.scss
- app/views/submissions/new.html.haml
RMI-295
Feedback from changes
No
[X] Bug fix
Visually checking.
> RMI-295-PO-Wording-Update

- CHANGELOG.md
- app/views/submissions/new.html.haml
RMI-295
QA feedback
N
[X] Bug fix
Visually checking.
> RMI-295-QA-Feedback-Updates

- CHANGELOG.md
- app/views/shared/_footer.html.haml
RMI-27
Feedback link required.
No
Locally visual check.
> RMI-27-Add-Feedback-Link-Footer

- CHANGELOG.md
- app/views/submissions/new.html.haml
RMI-300
Wave Accessibility Report results.
No.
[X] Bug fix
> RMI-300-Fix-Accessibility-Missing-Label

- app/views/submissions/new.html.haml
> RMI-300-Update-Label

- CHANGELOG.md
- app/views/submissions/validation_failed.html.haml
RMI-299
Wave Accessibility Report
No
[X] Bug fix
> RMI-299-Fix-Aria-Reference

- app/views/tasks/history.html.haml
Fixed framework column width following feedback
https://crowncommercialservice.atlassian.net/browse/RMI-37
QA feedback
No.
Manually
> fixed framework column width

- CHANGELOG.md
Missing features in prod, that were released.
[X] Bug fix
> Fix-Missing-Features

- CHANGELOG.md
- app/views/tasks/history.html.haml
We were missing some features that were previously released.
[X] Bug fix
> Develop Into Master - Fix Missing Features

- .travis.yml
- CF/deploy-app.sh
- CHANGELOG.md
- Gemfile
- Gemfile.lock
RMI-343
GDS support for ruby 2.5.7 is ending
No
[X] Breaking change
> Merge dev into conclave for ruby update

- CHANGELOG.md
- app/helpers/application_helper.rb
RMI-348
Link url has been changed by provider.
No.
[X] Bug fix
Please describe the tests that you ran to verify your changes.
> RMI-348-Update-Survey-URL

- CHANGELOG.md
- app/controllers/tasks_controller.rb
- app/views/kaminari/_first_page.html.haml
- app/views/kaminari/_gap.html.haml
- app/views/kaminari/_last_page.html.haml
- app/views/kaminari/_next_page.html.haml
- app/views/kaminari/_page.html.haml
- app/views/kaminari/_paginator.html.haml
- app/views/kaminari/_prev_page.html.haml
- app/views/tasks/_completed_tasks.html.haml
- app/views/tasks/history.html.haml
- config/locales/en.yml
- spec/features/user_can_sort_completed_tasks.rb
- spec/requests/tasks_spec.rb
RMI-314
RMI-315
Restore front end work done in staging
No
Fully tested prev.
> RMI-314 & 315 Restore

- app/controllers/sessions_controller.rb
- config/initializers/omniauth.rb
- config/routes.rb
RMI-335
Conclave SSO Integration work epic.
No.
Successfully logged in and out, repeatably.
> RMI-335-Conclave-SSO-Login-Flow

- CF/manifest-template.yml
- CF/user-services.json
- config/initializers/omniauth.rb
RMI-335
There was a small bug, that needed fixing from the conclave login flow release.
No.
[X] Bug fix
Successfully logged in.
> RMI-335-Conclave-Login-Flow-Minor-Update

- CHANGELOG.md
- Gemfile
- Gemfile.lock
Update changelog for new release.
https://crowncommercialservice.atlassian.net/browse/RMI-504
New release and address a vulnerability.
No.
[X] Bug fix
Ren test and checks. Advised by Snyk and Dependabot.
> Update changelog and fix vulnerability in addressable dependency

- app/views/submissions/completed.html.haml
Reverts Crown-Commercial-Service/DataSubmissionService#478
> Revert "Feature/rmi 341 customer effort score"

- CHANGELOG.md
- app/controllers/customer_effort_scores_controller.rb
- app/models/api/customer_effort_score.rb
- app/views/submissions/completed.html.haml
- config/routes.rb
- spec/features/user_can_submit_feedback_spec.rb
- spec/requests/customer_effort_scores_spec.rb
- spec/support/api_helpers.rb
Reverts Crown-Commercial-Service/DataSubmissionService#482
> Revert "RMI-341-revert"

- CHANGELOG.md
> Update changelog release 84

- CHANGELOG.md
> Release 85 changelog update

- CHANGELOG.md
> Changelog update for release 86

- CHANGELOG.md
- config/initializers/content_security_policy.rb
Amend Content Security Policy
https://crowncommercialservice.atlassian.net/browse/RMI-516
Glassbox not working
No
[X] Bug fix
N/A
> RMI-516 - update

- config/initializers/content_security_policy.rb
Updated content security policy
https://crowncommercialservice.atlassian.net/browse/RMI-516
To allow glassbox to work correctly
No
N/A
> RMI-516 CSP update

- config/environments/production.rb
> Snyk update - addressing deploy build error

- CHANGELOG.md
> Changelog update for release 88

- CHANGELOG.md
> updated changelog for release 89

- CHANGELOG.md
> Changelog update for release 93

- CHANGELOG.md
> Changelog update for release 94

- .rubocop.yml
- CF/manifest-template.yml
- Gemfile
- Gemfile.lock
Addressing buildpack issue causing deployment failure for this ticket
https://crowncommercialservice.atlassian.net/browse/RMI-620
Deployment failure
No
[X] Maintenance
Manual testing
> RMI-620 - update

- Gemfile.lock
Addressing dependency issue that caused a deployment failure
https://crowncommercialservice.atlassian.net/browse/RMI-620
Deployment failure
No
[X] Maintenance
N/A
> RMI-620 - update 2

- CHANGELOG.md
> Changelog update for release 95

- app/views/tasks/show.html.haml
https://crowncommercialservice.atlassian.net/browse/RMI-427
Added thousands separator for invoice amount in show task view
Improving readability
No
N/A
> RMI-247 - Update

- CHANGELOG.md
> Changelog update for release 96

- CHANGELOG.md
> CHANGELOG update for release 97

- CHANGELOG.md
> Further CHANGELOG update for release 97

- .travis.yml
- CHANGELOG.md
- [RMI-627: Improve loading time of URN list page](https://crowncommercialservice.atlassian.net/browse/RMI-627)
- [RMI-630: Minor content updates for URN list page](https://crowncommercialservice.atlassian.net/browse/RMI-630)
- [RMI-637: fix for GPG error in build](https://crowncommercialservice.atlassian.net/browse/RMI-637)
Improve user experience
Changes in API app should be released simultaneously
Feature, unit and manual testing
> Release/97 - build fix

- app/views/tasks/show.html.haml
- spec/requests/tasks_spec.rb
Changed submitted by to show email rather than name
https://crowncommercialservice.atlassian.net/browse/RMI-631?focusedCommentId=85872
Improve user experience
Changes to API app
Unit and manual testing
> RMI-631 Update

- CHANGELOG.md
> Changelog update for release 98

- k8s-buildkit-job.yaml
Link to the JIRA ticket and a summary of the change.
Provide details about why this change was needed.
List all the dependencies.
[ ] Bug fix
[ ] New feature 
[ ] Breaking change 
[ ] This change requires a documentation update
Please describe the tests that you ran to verify your changes.
> Fix ECR repo names for staging and prod

- CHANGELOG.md
> Changelog update for release 99

- Gemfile.lock
Addressing deployment issue around bundling gems
Original PR: https://github.com/Crown-Commercial-Service/DataSubmissionService/pull/646
> RMI-663 Update 1

- config/initializers/content_security_policy.rb
- public/maintenance.html
Fixing wording and styling issues with maintenance page
https://crowncommercialservice.atlassian.net/browse/RMI-670
User experience
No
Manually
> RMI-670 update

- CHANGELOG.md
> Changelog update for release 101

- CHANGELOG.md
> Changelog update for release 102

- app/assets/stylesheets/components/_all.scss
- app/assets/stylesheets/components/notification/_notification.scss
Updated notification styling
https://crowncommercialservice.atlassian.net/browse/RMI-652
QA feedback
No
Manually
> RMI-652 update

- CHANGELOG.md
> Changelog update for release 104

- CHANGELOG.md
> Changelog update for release 105

- CHANGELOG.md
> Changelog update for release 106

- app/assets/javascripts/application.js
- app/assets/javascripts/gtm-events.js
- app/views/agreements/_agreements.html.haml
- app/views/submissions/in_review.html.haml
- app/views/submissions/ingest_failed.html.haml
- app/views/submissions/new.html.haml
- app/views/tasks/_task.html.haml
- app/views/tasks/correct.html.haml
- app/views/tasks/show.html.haml
- app/views/urns/index.html.haml
- [RMI-717: view search results gtm event](https://crowncommercialservice.atlassian.net/browse/RMI-717)
- [RMI-706: doc upload and download gtm events](https://crowncommercialservice.atlassian.net/browse/RMI-706)
Improve event tracking data
No
Manually
> Feature/rmi 706 and Feature/rmi 717 view search results, doc upload and doc download gtm events

- CHANGELOG.md
> Changelog update for release 107

- app/assets/javascripts/gtm-events.js
- app/views/submissions/new.html.haml
- [RMI-707: accordion_use and search_filter gtm events](https://crowncommercialservice.atlassian.net/browse/RMI-707)
Improve event tracking data
No
Manually
> RMI-707: Implement accordion_use and search_filter gtm events

- app/assets/javascripts/gtm-events.js
- [RMI-718: cta_button_click, tab_navigation and login](https://crowncommercialservice.atlassian.net/browse/RMI-718)
Improve event tracking data
No
Manually
> RMI-718: Implement cta_button_click, tab_navigation and login gtm events

- config/environments/production.rb
Fix docker-build in jenkins 
https://crowncommercialservice.atlassian.net/browse/NRMI-75
To allow deployments to resume
No
[X] Bug fix
Manually
> NRMI-75: fix docker build

- CHANGELOG.md
> Changelog update for release 108

- CHANGELOG.md
> Changelog update for release 109

- CHANGELOG.md
> Changelog update for release 111

- CHANGELOG.md
> Changelog update for release 112

- app/controllers/errors_controller.rb
- app/views/errors/auth_failure.html.haml
- [NRMI-128: Improved error messaging for account lockout policy
](https://crowncommercialservice.atlassian.net/browse/NRMI-128)
To avoid user confusion
No
[X] Bug fix
Manually
> NRMI-128 update

- CHANGELOG.md
> Changelog update for release 113
